### ISSUE TITLE
DemoBench StartNode not working at Americas conference 

### ISSUE THREAD

**Issue by ediphy-cmurphy** [corda/corda#747] opened 2017-05-26 12:04 UTC
The issue I had with the app at the conference which I discussed with both Richard and Mike where the StartNode button was not clickable is not reproduced when I tried again today. App seems to be behaving normally now but odd behaviour yesterday.

**Comment by mikehearn** [comment] 2017-05-26 16:08
The mystery deepens.

We'll keep this issue around for a while in case anyone else sees it. The situation on the laptop I examined at the conference was like this:

* DemoBench started without any errors printed to the console. It was the latest version downloaded from the website for macOS.
* The app started and the UI thread was responsive at all times. Hovering over buttons would highlight them, etc.
* We could type into the edits and the auto-suggest boxes worked.
* However widgets were not clickable. Attempting to click start node did not even depress the button at all.

I have not seen such a situation before: I took stack traces of the app and there were no deadlocks or other issues, and at any rate, the UI stayed responsive throughout.

**Comment by mikehearn** [comment] 2017-06-13 08:05
Nobody has reported this before or since - did you see it again at all? I'm provisionally closing this now as we have no idea how to reproduce it and the problem went away by itself, so it may have been a local laptop issue. If it crops up again we'll reopen.

**Closed by mikehearn** 2017-06-13 08:05 UTC

**Comment by ediphy-cmurphy** [comment] 2017-06-13 08:12
No - it has not happened again. Will let you know if it reoccurs.

Chris.
