### ISSUE TITLE
Out of order received transactions cause invalid marking of spent/unspent

### ISSUE THREAD

**Issue by Quiark** [corda/corda#4484] opened 2019-01-02 07:54 UTC
Maybe I'm missing something but this happened

We have transactions A → B → C created by some other parties and our node (as participant) receives them out of order (first B → C and later A → B). In this case our vault will end up having both B and C marked as unspent because it doesn’t make the effort on the successors of B during marking B and transaction resolution for verification (done when receiving B → C) does fetch A → B but does not record anything about it.

The assumption I’m making here is that only one (the latest seen) state should be marked as unspent in the vault and thus this behaviour is a bug.

Found with Corda 3.3, didn't see any code change fixing this on master either.

**Comment by cryptoblk-viche** [comment] 2019-01-07 02:38
More details about issue -

Say we have transaction graph txA -> state A -> txB -> state B, both tx initiated by Node 1 and involved Node 2. Node 2 unfortunately receives txB before txA, it resulted in two unconsumed states:
1. Node receives txB via Send/ReceiveTransactionFlow called from FinalityHandler
    * Node receives txA via subFlow(ResolveTransactionsFlow)
    * Node does not record state A since ResolveTransactionsFlow uses StatesToRecord.NONE (https://github.com/corda/corda/blob/master/core/src/main/kotlin/net/corda/core/internal/ResolveTransactionsFlow.kt#L96)
    * Node records state B unconsumed; since there is no state A in the vault, it is not marked as consumed (https://github.com/corda/corda/blob/master/node/src/main/kotlin/net/corda/node/services/vault/NodeVaultService.kt#L158)
2. Node receives txA via Send/ReceiveTransactionFlow called from FinalityHandler
    * Node records state A unconsumed.
    * Now A and B are both unconsumed.

Node 1 - Vault (correct)
![microsoftteams-image 2](https://user-images.githubusercontent.com/41135465/50746085-5dbbd380-1268-11e9-8d01-1115a4bf6b0d.png)

Node 2 - Vault (wrong)
![microsoftteams-image 3](https://user-images.githubusercontent.com/41135465/50746077-509ee480-1268-11e9-9874-300f0eeb3aeb.png)

**Comment by roger3cev** [comment] 2019-01-07 10:11
@cryptoblk-viche Can you post your code that creates transaction A and B - would help us to debug. We are looking into a similar problem at the moment. Cheers!

**Comment by roger3cev** [comment] 2019-01-07 10:13
Also, can you try the same CorDapp on Corda 4 and report if you experience the same behaviour. Cheers!

**Comment by roger3cev** [comment] 2019-01-07 17:40
@Quiark is this on enterprise or open source?

**Comment by suweicong** [comment] 2019-01-08 02:51
could you also provides us the two nodes’ log files and persistence.mv.db files, if possible?

**Comment by JamesHR3** [comment] 2019-01-08 17:10
@Quiark @cryptoblk-viche This is happening due to a race condition in Corda, as indicated in CORDA-2402. We think this can be mitigated by reducing the chances of the condition happening, while we come up with a full solution. We should be able to produce a patch to do this, and from looking at your code I think this may help. Did you reproduce the problem using some test setup? If we were to provide a patch release, would you be able to check that it helps with the problem? And just to double check - are you running Open Source 3.3, or a different version?

**Comment by suweicong** [comment] 2019-01-09 01:33
Hi @JamesHR3 , i checked with Aaron, they are running on OS 3.3.

**Comment by Quiark** [comment] 2019-01-09 06:59
We don't have any steps to reproduce this apart from letting it run for 2 weeks. We can deploy a patched version to try but would need that in source form because we have backported a fix for MS SQL. We are using open source 3.3.

**Comment by JamesHR3** [comment] 2019-01-09 16:59
I've pushed the mitigation patch to v3.3-finality-race-reduction, which is a branch based on release-V3.X.

**Comment by mikehearn** [comment] 2019-07-05 12:44
This was fixed in Corda 4.0

**Closed by mikehearn** 2019-07-05 12:44 UTC
Labels: bug
