### ISSUE TITLE
Corda stops persisting PersistentState in db after ConstraintViolationException

### ISSUE THREAD

**Issue by nikitin01** [corda/corda#3482] opened 2018-07-02 08:30 UTC
If I get ConstraintViolationException when corda is saving PersistentState to db due to @Column(unique =true), transaction does not rollback and commits with new LinearState. And then corda stops saving PersistentState at all and other transactions with LinearStates just commit without exceptions. Is it a known issue?

**Comment by joeldudleyr3** [comment] 2018-07-09 11:08
Tracked here: https://r3-cev.atlassian.net/browse/CORDA-1742.

**Comment by lankydan** [comment] 2018-08-04 08:57
I'll pick this up when i can

**Comment by lankydan** [comment] 2018-08-26 06:50
I have tested this and cannot get it to fail with the information included in this issue. I'll add a commit with tests around this so there is confirmation that it works. If more info could be provided on how to get it to fail then I can look into it again.

**Comment by mikehearn** [comment] 2018-08-27 20:11
@lankydan I think you can't reproduce it because it was already fixed, but the bug and JIRA may not have been updated. @tudor-malene may remember the details: I think this was due to a loose coupling between components (an observable that was swallowing exceptions).

**Comment by tudor-malene** [comment] 2018-08-29 07:37
This was fixed here: https://r3-cev.atlassian.net/browse/CORDA-1847

@joeldudleyr3, we can close this one

**Comment by joeldudleyr3** [comment] 2018-09-19 10:56
Thanks Tudor. Also fixed by https://github.com/corda/corda/pull/3849 :)

**Closed by joeldudleyr3** 2018-09-19 10:56 UTC
