### ISSUE TITLE
Multiple Observables arrived with the same ID

### ISSUE THREAD

**Issue by trferreira-BR** [corda/corda#2300] opened 2017-12-28 11:57 UTC
Hi,

I am using V2.0 Corda and I create an Observable in web app (Spring Boot) to receive information from Node Corda by RPC and some moments It throws an exception with message 'Multiple Observables arrived with the same ID'.

That problem is possible to see because I maped in logback file an appender/logger in our web app:

`<logger name="org.apache.activemq.artemis.core" level="error" additivity="false">
      <appender-ref ref="ROLLING-FILE-APPENDER"/>
</logger>`

obs.: We identified that problem since version V1.0 Corda.

The log trace:
2017-12-19 09:27:11 - AMQ214000: Failed to call onMessage
com.esotericsoftware.kryo.KryoException: java.lang.IllegalArgumentException: Multiple Observables arrived with the same ID ObservableId(toLong=8174636548186332080)
Serialization trace:
updates (net.corda.core.messaging.DataFeed)
value (net.corda.core.utilities.Try$Success)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:144)
	at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.read(CompatibleFieldSerializer.java:147)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
	at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.read(CompatibleFieldSerializer.java:147)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
	at net.corda.nodeapi.internal.serialization.AbstractKryoSerializationScheme$deserialize$$inlined$use$lambda$1$1.invoke(SerializationScheme.kt:209)
	at net.corda.nodeapi.internal.serialization.AbstractKryoSerializationScheme$deserialize$$inlined$use$lambda$1$1.invoke(SerializationScheme.kt:152)
	at net.corda.nodeapi.internal.serialization.AbstractKryoSerializationScheme.withContext(SerializationScheme.kt:191)
	at net.corda.nodeapi.internal.serialization.AbstractKryoSerializationScheme.access$withContext(SerializationScheme.kt:152)
	at net.corda.nodeapi.internal.serialization.AbstractKryoSerializationScheme$deserialize$$inlined$use$lambda$1.execute(SerializationScheme.kt:206)
	at com.esotericsoftware.kryo.pool.KryoPoolQueueImpl.run(KryoPoolQueueImpl.java:61)
	at net.corda.nodeapi.internal.serialization.AbstractKryoSerializationScheme.deserialize(SerializationScheme.kt:205)
	at net.corda.nodeapi.internal.serialization.SerializationFactoryImpl$deserialize$1$1.invoke(SerializationScheme.kt:115)
	at net.corda.core.serialization.SerializationFactory.withCurrentContext(SerializationAPI.kt:53)
	at net.corda.nodeapi.internal.serialization.SerializationFactoryImpl$deserialize$1.invoke(SerializationScheme.kt:115)
	at net.corda.nodeapi.internal.serialization.SerializationFactoryImpl$deserialize$1.invoke(SerializationScheme.kt:95)
	at net.corda.core.serialization.SerializationFactory.asCurrent(SerializationAPI.kt:67)
	at net.corda.nodeapi.internal.serialization.SerializationFactoryImpl.deserialize(SerializationScheme.kt:115)
	at net.corda.nodeapi.RPCApi$ServerToClient$Companion.fromClientMessage(RPCApi.kt:234)
	at net.corda.client.rpc.internal.RPCClientProxyHandler.artemisMessageHandler(RPCClientProxyHandler.kt:242)
	at net.corda.client.rpc.internal.RPCClientProxyHandler.access$artemisMessageHandler(RPCClientProxyHandler.kt:65)
	at net.corda.client.rpc.internal.RPCClientProxyHandler$start$3.invoke(RPCClientProxyHandler.kt:192)
	at net.corda.client.rpc.internal.RPCClientProxyHandler$start$3.invoke(RPCClientProxyHandler.kt:65)
	at net.corda.client.rpc.internal.RPCClientProxyHandlerKt$sam$MessageHandler$cbde6789.onMessage(RPCClientProxyHandler.kt)
	at org.apache.activemq.artemis.core.client.impl.ClientConsumerImpl.callOnMessage(ClientConsumerImpl.java:997)
	at org.apache.activemq.artemis.core.client.impl.ClientConsumerImpl.access$400(ClientConsumerImpl.java:49)
	at org.apache.activemq.artemis.core.client.impl.ClientConsumerImpl$Runner.run(ClientConsumerImpl.java:1120)
	at org.apache.activemq.artemis.utils.OrderedExecutorFactory$OrderedExecutor$ExecutorTask.run(OrderedExecutorFactory.java:101)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Multiple Observables arrived with the same ID ObservableId(toLong=8174636548186332080)
	at net.corda.client.rpc.internal.RpcClientObservableSerializer.read(RPCClientProxyHandler.kt:428)
	at net.corda.client.rpc.internal.RpcClientObservableSerializer.read(RPCClientProxyHandler.kt:404)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
	... 31 common frames omitted

**Comment by exFalso** [comment] 2018-01-25 15:19
@trferreira-BR Thank you for the report! I remember getting this error on artemis failover, which happens if you restart the node while the webserver is running. Were these exceptions happening the same time the node was restarted?

**Comment by trferreira-BR** [comment] 2018-01-29 10:10
@exFalso You're welcome. No, These exceptions doesn't happen when the node is restarted, It happens any time. Let me know if you need more specific details. THX

**Comment by exFalso** [comment] 2018-02-02 18:24
@trferreira-BR Can you paste the code that does the query in the spring server please?

We may need to put in *some* dedupe logic into the RPCClient, Artemis seems to duplicate some non-durable messages

**Comment by trferreira-BR** [comment] 2018-02-05 10:09
@exFalso Sure. I needed to change only the state's name to mask information about my project, but the code is that. I'm sending a new log updated.

`// Starts streaming States to the websocket.
    init {
        val vaultQueryCriteria = QueryCriteria.VaultQueryCriteria(Vault.StateStatus.ALL)

        val pageSpecificationLast = PageSpecification(pageSize = 20, pageNumber = 1)
        val stateVaultObservable = rpc.proxy.vaultTrackByWithPagingSpec(IOUState::class.java, vaultQueryCriteria, pageSpecificationLast)
        stateVaultObservable.updates.subscribe { update ->
            update.produced.forEach { (state) ->
                val stateJson = state.data.toJson()
                template.convertAndSend("/stompresponseproduced", stateJson)
            }
        }
    }`

[rolling-file-appender.log](https://github.com/corda/corda/files/1694639/rolling-file-appender.log)

**Comment by exFalso** [comment] 2018-02-05 19:33
Thank you!

I have trouble reproducing this, but judging from the timestamps this happens fairly rarely, which makes me think flaky network may be the cause. If a failover happens after the message is sent but before the server gets an ACK from the client, then on reconnect the observable (or in fact any RPC reply) will be re-sent.

In the above cases where Observa*ble*s are sent, and in the case of direct replies to RPCs this is actually fine (aside from the error print), however this can also happen for Observa*tion*s, which would dupe some events in the Observables, which is a pretty bad bug!

Regardless of whether the root cause is flaky network or something else, the solution to the duping would be.. well, deduping. I added a ticket and self-assigned it (https://r3-cev.atlassian.net/browse/CORDA-984), a fix should be in master fairly soon.

**Comment by mikehearn** [comment] 2018-02-12 16:45
Artemis / MQ software in general is meant to handle de-duping for us - from looking at the code we don't seem to be using this feature _at all_. Are you sure we need to write this again at the application level?

**Comment by exFalso** [comment] 2018-02-13 15:03
@mikehearn yes, artemis does do deduping, however it doesn't seem to dedupe correctly on failover when there are some pending non-acked messages. Which kind of makes sense, it doesn't know what messages were lost.

I played around with the rpc code some more and made it work without a session pool without sacrificing performance. This seemed to reduce the duplication, at least on client kick.

However it revealed another issue, namely when the client is kicked sometimes it fails over during the test and *artemis starts delivering out of order messages*. I'm currently diagnosing this.

**Closed** 2018-02-19 16:25 UTC
Labels: bug
