### ISSUE TITLE
Gradle build demands to be run from inside a git repository

### ISSUE THREAD

**Issue by eacoeytaux** [corda/corda#1304] opened 2017-08-22 17:02 UTC
I'm on OSX, and am trying to run the demo described in https://docs.corda.net/running-the-demos.html#trader-demo but when I run `./gradlew samples:trader-demo:deployNodes` I get the following message:
`:buildSrc:compileJava NO-SOURCE`
`:buildSrc:compileGroovy UP-TO-DATE`
`:buildSrc:processResources NO-SOURCE`
`:buildSrc:classes UP-TO-DATE`
`:buildSrc:jar UP-TO-DATE`
`:buildSrc:assemble UP-TO-DATE`
`:buildSrc:compileTestJava NO-SOURCE`
`:buildSrc:compileTestGroovy NO-SOURCE`
`:buildSrc:processTestResources NO-SOURCE`
`:buildSrc:testClasses UP-TO-DATE`
`:buildSrc:test NO-SOURCE`
`:buildSrc:check UP-TO-DATE`
`:buildSrc:build UP-TO-DATE`
`FAILURE: Build failed with an exception.`
`* Where:`
`Build file '/Users/<myusername>/Documents/Corda/corda-master/build.gradle' line: 79`
`* What went wrong:`
`A problem occurred evaluating root project 'corda-project'.`
`> repository not found: /Users/<myusername>/Documents/Corda/corda-master`
The repository `/Users/<myusername>/Documents/Corda/corda-master` is the downloaded git repo and where I'm running the command from.  I am sure my username is not misspelled.

**Comment by eacoeytaux** [comment] 2017-08-30 18:10
So it turns out the command will only work if the repository is cloned with `git clone` and will not work if the repo is directly downloaded.  However after getting past this step the command `./gradlew samples:trader-demo:runBuyer` returns

`Publication named 'corda-jfx' does not exist for project ':client:jackson' in task ':client:jackson:artifactoryPublish'.
Publication named 'corda-mock' does not exist for project ':client:jackson' in task ':client:jackson:artifactoryPublish'.
Publication named 'corda-rpc' does not exist for project ':client:jackson' in task ':client:jackson:artifactoryPublish'.
Publication named 'corda-core' does not exist for project ':client:jackson' in task ':client:jackson:artifactoryPublish'.
Publication named 'corda' does not exist for project ':client:jackson' in task ':client:jackson:artifactoryPublish'.
Publication named 'cordform-common' does not exist for project ':client:jackson' in task ':client:jackson:artifactoryPublish'.
Publication named 'corda-finance' does not exist for project ':client:jackson' in task ':client:jackson:artifactoryPublish'.
Publication named 'corda-node' does not exist for project ':client:jackson' in task ':client:jackson:artifactoryPublish'.
Publication named 'corda-node-api' does not exist for project ':client:jackson' in task ':client:jackson:artifactoryPublish'.
Publication named 'corda-test-common' does not exist for project ':client:jackson' in task ':client:jackson:artifactoryPublish'.
Publication named 'corda-test-utils' does not exist for project ':client:jackson' in task ':client:jackson:artifactoryPublish'.
Publication named 'corda-verifier' does not exist for project ':client:jackson' in task ':client:jackson:artifactoryPublish'.
Publication named 'corda-webserver-impl' does not exist for project ':client:jackson' in task ':client:jackson:artifactoryPublish'.
Publication named 'corda-webserver' does not exist for project ':client:jackson' in task ':client:jackson:artifactoryPublish'.`

plus many more similar errors.

**Comment by mikehearn** [comment] 2017-08-31 08:42
I think those messages are actually harmless, albeit alarmingly worded. @Clintonio has said in the past it's hard to suppress them but I'm sure we can find a way?!

Not working unless the directory is a git repo is a new one. That's probably a piece of code that's finding the current commit hash - we should fix it. I'll rename this bug to clarify.

**Comment by chrisr3** [comment] 2017-09-18 13:44
This issue could be caused by [ProjectStructure.kt](https://github.com/corda/corda/blob/master/testing/test-utils/src/main/kotlin/net/corda/testing/ProjectStructure.kt).

Does creating a fake ".git" directory at the project root fix things?

**Comment by DikshikaJain** [comment] 2018-06-15 06:29
is this issue fixed?

**Comment by mikehearn** [comment] 2018-10-04 16:35
There are two issues reported here. One is a bit unclear (downloaded git repo that wasn't a clone?) and I'm not sure it's a bug, or not one worth fixing.

The other is about errors that I used to see but no longer do. So I'm closing this as fixed.

**Closed by mikehearn** 2018-10-04 16:35 UTC
Labels: bug
