### ISSUE TITLE
RPC exceptions cascade while redeploying nodes for samples

### ISSUE THREAD

**Issue by m4ksio** [corda/corda#1416] opened 2017-09-04 17:00 UTC
WIP on IRS sample using Spring boot as a standalone application to communicate with nodes over RPC. 
Standard setup as described in the doc, startup nodes  (project in samples/irs-demo-spring/cordapp ) then build and start Spring boot (```gradlew :samples:irs-demo-spring:webapp:build && cd samples/irs-demo-spring/webapp && java -jar -jar build/libs/web-0.0.1-SNAPSHOT.jar``` to start webapp (Nodes must be up and running first)
Navigate to http://localhost:8080/#/create-deal to create a deal.
Then, shutdown all the nodes and the webapp. Run ":deployNodes" task from cordapp again, and start nodes again. Run webapp and try to create deal again - 
A cascade of RPC errors on webapp side, triggered by errors in serialization of yet another exception regarding key validation.

I was able to reproduce this quite reliably using above method.

Reproduced on https://github.com/corda/corda/commit/644933bab28fc139f8fdb6118823458e0294a3f3

Discussed with @exFalso  and @mnesbit

**Comment by m4ksio** [comment] 2017-09-05 09:21
Actually, its enough to just run the nodes again after shutting down (```./runnodes```) there is no need to use Gradle task ```deployNodes``` for the second time.

**Comment by mikehearn** [comment] 2017-09-05 09:45
I thought we had some code to ensure that exceptions that didn't serialise properly were passed as just Throwables with the message and stack trace ....

**Comment by exFalso** [comment] 2017-09-05 17:46
Managed to reproduce the RPC issue in a small test. It seems that Artemis redelivers *already acknowledged* messages for some reason when the consumer is kicked (the message ids are exactly the same). Will investigate more

**Comment by exFalso** [comment] 2017-09-11 09:16
An update on the RPC issue: The reason the client kick was triggered was because of an unserialisable object, however #1424 changed this behaviour, we now send serialisation errors to the client. This means the only way the kick can be triggered is an exception in the artemis send, and i think the only way to reliably do that is with slow consumption on the client side

**Comment by exFalso** [comment] 2017-09-21 11:10
I can't reproduce this anymore on master (not even with slow consumption), optimistically closing this.

**Closed by exFalso** 2017-09-21 11:10 UTC
Labels: bug
