### ISSUE TITLE
Serialization/Suspension of Kotlin for loops in Corda 4.3

### ISSUE THREAD

**Issue by RobMase** [corda/corda#5924] opened 2020-02-05 13:43 UTC
After upgrading to corda 4.3, we have experienced failing integration tests based on a DriverDSLImpl. The code under test that throws the exception is a Flow from the corda-solutions repository. But the underlying issue should be independent from that specific Flow. 

Below is the exception and the stack trace.

```
 java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_221]
	at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_221]
	at net.corda.businessnetworks.ledgersync.TransactionRecoveryFlow.call(TransactionRecoveryFlow.kt:71)
	at net.corda.businessnetworks.ledgersync.TransactionRecoveryFlow.call(TransactionRecoveryFlow.kt:21) 
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:274) ~[corda-node-4.3.jar:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:46) ~[corda-node-4.3.jar:?]
	at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1092) ~[quasar-core-0.7.11_r3-jdk8.jar:0.7.11_r3]
	at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:788) ~[quasar-core-0.7.11_r3-jdk8.jar:0.7.11_r3]
	at co.paralleluniverse.fibers.RunnableFiberTask.doExec(RunnableFiberTask.java:100) ~[quasar-core-0.7.11_r3-jdk8.jar:0.7.11_r3]
	at co.paralleluniverse.fibers.RunnableFiberTask.run(RunnableFiberTask.java:91) ~[quasar-core-0.7.11_r3-jdk8.jar:0.7.11_r3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_221]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.29.Final.jar:4.1.29.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
```

The relevant code snippet from the Flow:
```
@Suspendable
    override fun call() {
        // pre filter map to remove multilateral transactions.
        report.toList().map { (counterParty, findings) ->
            val session = initiateFlow(counterParty)
            findings.recoverable().filter {
                // only attempt to recover transactions that are not present.
                // this is intended to exclude multilateral transactions that have already been recovered
                serviceHub.validatedTransactions.getTransaction(it) == null
            }.also {
                session.send(it)
            }.map {
                subFlow(ReceiveTransactionFlow(session, statesToRecord = ALL_VISIBLE))
            }
        }
    }
```

Initially we tried using the nested loop below to remove the lambda the stack trace is pointing to, as suggested on a similar issue by Joel Dudley (https://stackoverflow.com/questions/47356340/quasar-npe-when-passing-a-kotlin-lambda-to-a-corda-flow).  

```
@Suspendable
    override fun call() {
        // pre filter map to remove multilateral transactions.
        val filteredFindings = report.toList().map { (counterParty, findings) ->
            Pair(counterParty, findings.recoverable().filter {
                // only attempt to recover transactions that are not present.
                // this is intended to exclude multilateral transactions that have already been recovered
                serviceHub.validatedTransactions.getTransaction(it) == null
            })
        }

        for (findingsPerParty in filteredFindings) {
            val session = initiateFlow(findingsPerParty.first)
            session.send(findingsPerParty.second)
            for (item in findingsPerParty.second) {
                subFlow(ReceiveTransactionFlow(session, statesToRecord = ALL_VISIBLE))
            }
        }
    } 
```
With that code still the same exception occurred. 

We could fix the issue by changing the above call function to utilize a nested for loop instead which is not iterating over the `List<SecureHash>` twice but only once:

```
@Suspendable
    override fun call() {
        // pre filter map to remove multilateral transactions.
        val filteredFindings = report.toList().map { (counterParty, findings) ->
            Pair(counterParty, findings.recoverable().filter {
                // only attempt to recover transactions that are not present.
                // this is intended to exclude multilateral transactions that have already been recovered
                serviceHub.validatedTransactions.getTransaction(it) == null
            })
        }

        for (findingsPerParty in filteredFindings) {
            val session = initiateFlow(findingsPerParty.first)
            session.send(findingsPerParty.second)
            for (i in 1..findingsPerParty.second.size) {
                subFlow(ReceiveTransactionFlow(session, statesToRecord = ALL_VISIBLE))
            }
        }
    }
```
So it seems there are issues with such constructs on `@Suspendable` functions.

**Comment by mikehearn** [comment] 2020-02-07 15:08
Can you examine the value of `Itr.expectedModCount` vs `ArrayList.modCount`? Is the latter zero?

I suspect I know what the issue is. `ArrayList.modCount` is marked as transient, so it'll be skipped by Kryo, but the iterator's `expectedModCount` isn't. After deserialization they won't match.

It can be fixed by customising the serialization of the iterators to zero the expectedModCount on deserialization.

**Comment by mikehearn** [comment] 2020-02-07 15:08
@joeldudleyr3

**Comment by ulrikrasmussen** [comment] 2020-02-17 13:39
This would still change the semantics of the code wouldn't it? If the code did a concurrent modification of the collection before blocking, then that would suppress the `ConcurrentModificationException` that would otherwise be thrown when the iterator fetches the next element.

**Comment by mnesbit** [comment] 2020-02-17 13:51
What is the 'report' variable here? Are we sure that isn't being modified by other threads/fibers? Needs to be an atomic snapshot if it is.

**Closed as completed** 2020-05-20 13:48 UTC
Labels: Triaged
