### ISSUE TITLE
MS SQL encrypted column not compatible with current Hibernate configuration

### ISSUE THREAD

**Issue by Quiark** [corda/corda#4017] opened 2018-10-03 01:41 UTC
MS SQL Server has a feature called Always Encrypted which implements clientside (in JDBC driver) data encryption and decryption (so the DB server never sees the key). Metadata about this encryption is still stored in the database so such a column will have a different data type.

MS SQL doesn't use the Blob data type, everything is just `VARBINARY` AFAIK. Corda transaction and attachment storage uses the `@Lob` JPA annotation.

Now if you put all these 3 conditions together, it won't work, the error message is 
```com.microsoft.sqlserver.jdbc.SQLServerException: The conversion from VARBINARYMAX to BLOB is unsupported```. Without encryption, the database is able to tolerate the `@Lob` annotation but not with it. Removing it seems to fix the problem but the real fix may be something like a custom MS SQL dialect so that it doesn't affect other database support.

**Comment by Quiark** [comment] 2018-10-05 07:08
Oh I should note I was using `mssql-jdbc` version `7.0.0.jre8` which I understand was the latest. I should probably try the same with 6.2 mentioned on enterprise corda docs.

**Comment by Quiark** [comment] 2018-10-05 09:43
Yeah same with `6.2`

**Comment by mikehearn** [comment] 2018-10-08 14:05
This sounds more like an issue with Hibernate than Corda?

**Comment by Quiark** [comment] 2018-10-09 02:58
Yeah it just seems MS SQL needs some special treatment in Hibernate configuration and unfortunately for me it doesn't manifest unless encryption is involved. I dug out the stack trace: 
[issue.txt](https://github.com/corda/corda/files/2458697/issue.txt)

**Comment by mikehearn** [comment] 2018-11-19 09:35
Do you know what the special treatment is? I'm inclined to say this is a Hibernate bug (or possibly a MS SQL driver bug) rather than a Corda bug. We aren't doing anything special here, as far as I know, we're just users of the frameworks. We could reopen this upstream in Hibernate and see what they say? If they fix it we'll bump our Hibernate dependency to pick up the fix.

**Comment by tudor-malene** [comment] 2018-11-19 10:05
From the stacktrace it appears that the bug is in the jdbc driver:

`Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The conversion from VARBINARYMAX to BLOB is unsupported.
	at com.microsoft.sqlserver.jdbc.DDC.convertBytesToObject(DDC.java:493) ~[mssql-jdbc-6.2.2.jre8.jar:?]`

I'm wondering if you could try to disable encryption on the blob columns and see if you can make it  work.
To try to narrow down the problem.

**Comment by Quiark** [comment] 2018-11-19 10:11
It works without encryption. My understanding is that Blob is not supposed to be used with MS SQL but they perhaps have some backward compatibility layer that allows it, but only without encryption.

**Comment by tudor-malene** [comment] 2018-11-19 10:33
We map the columns annotated with `@Lob` to `varbinary`.

And Hibernate is also doing that. 
See:
``	
public SQLServer2005Dialect() {
		registerColumnType( Types.BLOB, "varbinary(MAX)" );
``

What I meant is to try with "always encrypted", but disable it only on the `@Lob` columns - if that is possible.

**Comment by mikehearn** [comment] 2018-11-19 10:35
blob is not supposed to be using with MS SQL? Why not? This is news - do the docs say that anywhere? Why would a DB engine not support blob types, that's a pretty basic feature in any db engine.

**Comment by tudor-malene** [comment] 2018-11-19 10:40
They just call it `varbinary` . It's the same thing.
When you annotate a hibernate column with `@Lob` and the dialect is `SqlServer`, it will just map to and from varbinary.

**Comment by Quiark** [comment] 2018-11-19 10:51
> What I meant is to try with "always encrypted", but disable it only on the `@Lob` columns - if that is possible.

You mean enable always-encrypt globally but not use it on this column? It's per column and it works on other byte[] columns that I didn't encrypt.

Documentation about types is here https://docs.microsoft.com/en-us/sql/t-sql/data-types/binary-and-varbinary-transact-sql?view=sql-server-2017 and it doesn't mention BLOB type. 

I guess the mapping to varbinary is not working properly? Because in the stack trace it ends up going to `SQLServerResultSet.getBlob()` and then it complains that conversion to BLOB is unsupported.

**Comment by mikehearn** [comment] 2018-11-19 11:00
Apparently it *is* possible:

https://dba.stackexchange.com/questions/202873/is-it-possible-to-encrypt-varbinarymax-column-using-always-encrypted-feature

**Comment by tudor-malene** [comment] 2018-11-19 11:01
It is most likely some hibernate/jdbc driver mismatch when encryption is used.

We had another problem with blobs on postgres, and we solved it by creating a special "corda-blob" hibernate type.
See `DBCheckpoint` and `MapBlobToPostgresByteA`.

Worst case scenario, we could do something similar here, if nothing else works.

What I would suggest is to try and create a simple hibernate project that uses the same config, and tries to encrypt "blobs". 
Maybe there's some special hibernate  or jdbc settings, annotations, incantations that need to be made to make it work.
Once we know what that is, we can add it to the codebase.

**Comment by tudor-malene** [comment] 2018-11-19 11:32
Should we open this bug with Hibernate as @mikehearn suggested?

If it woks without `@Lob` then it is their bug.

**Comment by mikehearn** [comment] 2018-11-19 12:05
Yeah, if we can get a small repro case perhaps they'll be able to fix it. Alternatively we could step through Hibernate and try to figure out what's going on. `@Lob` should work and seems to be correct so it's not a Corda bug.

**Comment by Quiark** [comment] 2018-12-04 03:56
[mssql-aenc-0.3.zip](https://github.com/corda/corda/files/2642335/mssql-aenc-0.3.zip)

Here is a small example project for reproducing this problem.

**Comment by mikehearn** [comment] 2019-01-17 09:59
I suspect the issue here runs deeper. Always Encrypted mode is not a standard database. From the SQL Server docs:

> Although the client driver transparently encrypts and decrypts data, the application may need to be changed to adhere to requirements/limitations of Always Encrypted. For example, Always Encrypted only supports very limited operations on encrypted database columns. This is one of the reasons why we recommend you use Always Encrypted to protect truly sensitive data in selected database columns.

So it's not intended to be really compatible with SQL. Perhaps that's why it doesn't work.

I'm not sure we want to fix this. Supporting "Always Encrypted" mode would be a cool upgrade, but it would presumably impose severe limits on the types of queries Corda would then be able to make, forever. Those limits would also propagate through to applications - we'd need some way to mark apps as being Always Encrypted compatible, and verify that at load time, to stop people installing apps that would try to do queries that aren't workable with column encryption.

Neat feature, but right now we have our hands ultra-full with everything else that's going on. Supporting this mode would probably need to be treated as a product design decision, and that means we'd need to study in more depth exactly how we'd be binding our hands, and the hands of app developers. If important classes of queries can't be done that way, we'd need to carefully pick which columns are encrypted and how, and that in turn would require some sort of plausible threat model and security analysis so we don't e.g. encrypt some columns but leave the binary blob they were derived from unencrypted.

Given this, I'm inclined to close this bug report, not because it's a wrong or bad report, but more because having learned more, I'm not convinced this is a bug in Corda ... and maybe not even in Hibernate. If we fixed this issue we'd surely encounter others.

**Closed by mikehearn** 2019-01-17 09:59 UTC
Labels: enhancement

**Comment by ss361084** [comment] 2019-11-16 09:51
i also have same error with BigDecimal(18,5) datatype
when column not encrypted it will work and 
when i add column encryption then decimal(18,5) not inserted in database and show me error 
like, Opearnd type clash decimal(18,2) with incomapatibility with decimal(18,5)
what is solution??
currently i m using hibernate 5.0.1.Final,spring 4.3.18.RELEASE and mssql version 6.1.6.jre8-preview
