### ISSUE TITLE
Corda does not allow for data persistence across node restarts(because of H2 bug and more)

### ISSUE THREAD

**Issue by crazyquark** [corda/corda#1975] opened 2017-11-01 10:26 UTC
I am using in gradle version 1.0.0 of corda.

I wanted to have data persist across restarts of a node but I hit the following roadblocks:

- There is a bug in H2/Hibernate that prevents validating fields of type UUID(created as varbinary, validated as binary - fails at restart when validating), see [this](https://hibernate.atlassian.net/browse/HHH-9835)
- The VaultStatesLinear entity is affected by above issue
- I managed to bypass the above issue by hacking H2Dialect class but then I hit another issue, Corda tries to repeatedly insert network map info into the DB violating a unique constraint
- No way to switch to any other JDBC provider other than H2

I had to infer from code that in order to keep the DB from resetting itself one needs to add this to reference.conf (there is no documentation about this):
`
database: {
  initDatabase : false
}
`
But even so Corda will still try to insert network info in the DB and violate unique constraints.
I've given up for the moment but I think this will be a big issue in production environments.

**Comment by mikehearn** [comment] 2017-11-22 17:15
Sorry for the slow response. I've assigned this bug to people working on the network map code and the database code. I am surprised by this because I've restarted nodes lots of times and we do have tests which do that. So we should investigate ASAP.

Support for non-H2 databases is a feature that we're working on but it's currently targeted for the Enterprise edition.

**Comment by josecoll** [comment] 2017-11-22 18:00
Sounds rather odd.
Our schema definition of the field in question is:
`            @Column(name = "uuid", nullable = false)`
`            var uuid: UUID`
with no sizing constraint specified, so this is mapped by Hibernate to H2 as follows:
`uuid binary not null`
(which doesn't quite match up to the observation above).

**Comment by mikehearn** [comment] 2017-11-23 10:05
The issue is caused by the (somewhat misleadingly named) initDatabase property. Even when set to true data will not be deleted. However the node will try to apply schema updates. When set to false as you have done, we can reproduce this issue. We're working on it now.

**Comment by sollecitom** [comment] 2017-11-23 11:43
I am able to reproduce the bug described, provided I manually set `database: { initDatabase : false }`.

There are 2 issues opened against Hibernate and H2 for this problem (https://hibernate.atlassian.net/browse/HHH-9835 and https://github.com/h2database/h2database/issues/345), but both are blaming the other and saying they won't fix it.

`database: { initDatabase : true }` is Corda's default, and it does not instruct the node to wipe the vault in any way. What it does is to instruct Hibernate to recreate / update the schema on startup. This has no effect on the data, and it has been tested with 1.0 and 2.0 as part of their release and by me this morning.

When `database: { initDatabase : false }` is specifically set inside `reference.conf` (or better, inside a node's `node.conf`, requiring no changes to Corda), Hibernate instead validates the existing schema, and the issue with H2 metadata arises.

Given the above, a solution would be not to explicitly add `database: { initDatabase : false }` to either `reference.conf` or a node's `node.conf`.

@crazyquark if you still find that your vault data is reset in between restarts, please let us know your folders/files structure and scripts/code so that we can investigate further.

**Comment by mikehearn** [comment] 2017-11-23 14:23
OK, so I see a few things we can fix here:

1. `initDatabase` is a rather misleading name for what it does. It's more like `updateSchemas` isn't it? I'd have made the same assumption about it wiping the database. Let's rename it.
2. Corda should work given a valid combination of config params. It currently doesn't. I see that in the Hibernate bug report the reporter gives a simple workaround involving making a subclass of the H2 Dialect that simply makes all binary fields always VARBINARY. Can we look at that and see if the workaround applies here? We haven't commited to DB stability yet, so we can still make fixes like that quite easily.

**Comment by josecoll** [comment] 2017-11-23 14:26
It means "create schemas if they don't exist" otherwise "update them".

**Comment by mikehearn** [comment] 2017-11-23 14:28
Yes, but init usually implies reset to the starting state. In this case "initialisation" can actually mean "do nothing at all", which is odd.

**Comment by crazyquark** [comment] 2017-11-27 06:53
Hi, indeed, I discovered that the issue was that the build environment was using a new folder at each run and that's why the data was actually not persisted. So the bug is not actually a bug anymore.

**Closed** 2018-04-27 12:46 UTC
