### ISSUE TITLE
`java.lang.NullPointerException: null` when suspending despite `@Suspendable`

### ISSUE THREAD

**Issue by joeldudleyr3** [corda/corda#3751] opened 2018-08-07 09:13 UTC
See https://github.com/corda/cordapp-example/tree/joel-bug-branch.

The flow is defined in Java as follows:

```
package com.example.flow;

import co.paralleluniverse.fibers.Suspendable;
import com.google.common.collect.ImmutableList;
import kotlin.Triple;
import net.corda.core.flows.*;
import net.corda.core.identity.Party;

import java.util.List;

public class ExampleFlow {
    @InitiatingFlow
    @StartableByRPC
    public static class Initiator extends FlowLogic<Void> {
        private final Party otherParty;

        public Initiator(Party otherParty) {
            this.otherParty = otherParty;
        }

        @Suspendable
        @Override
        public Void call() throws FlowException {
            FlowSession otherPartySession = initiateFlow(otherParty);
            List<FlowSession> sessions = ImmutableList.of(otherPartySession);
            sessions.forEach( it -> sendAMessage(it, new Triple("a", "b", "c")));
            return null;
        }
    }

    @InitiatedBy(Initiator.class)
    public static class Acceptor extends FlowLogic<Void> {

        private final FlowSession otherPartyFlow;

        public Acceptor(FlowSession otherPartyFlow) {
            this.otherPartyFlow = otherPartyFlow;
        }

        @Suspendable
        @Override
        public Void call() throws FlowException {
            otherPartyFlow.receive(Triple.class).unwrap(it -> { return it; });
            return null;
        }
    }

    @Suspendable
    private static Void sendAMessage(FlowSession session, Triple t) {
        session.send(t);
        return null;
    }
}
```

Running it (e.g. by running the flow tests here: https://github.com/corda/cordapp-example/blob/joel-bug-branch/java-source/src/test/java/com/example/flow/IOUFlowTests.java) gives the following exception:

```
java.lang.NullPointerException: null
    at net.corda.node.services.statemachine.FlowStateMachineImpl.suspend(FlowStateMachineImpl.kt:514) ~[corda-node-3.2-corda.jar:?]
    at net.corda.node.services.statemachine.FlowStateMachineImpl.sendInternal(FlowStateMachineImpl.kt:370) ~[corda-node-3.2-corda.jar:?]
    at net.corda.node.services.statemachine.FlowStateMachineImpl.initiateSession(FlowStateMachineImpl.kt:434) ~[corda-node-3.2-corda.jar:?]
    at net.corda.node.services.statemachine.FlowStateMachineImpl.initiateSession$default(FlowStateMachineImpl.kt:423) ~[corda-node-3.2-corda.jar:?]
    at net.corda.node.services.statemachine.FlowStateMachineImpl.send(FlowStateMachineImpl.kt:246) ~[corda-node-3.2-corda.jar:?]
    at net.corda.node.services.statemachine.FlowSessionImpl.send(FlowSessionImpl.kt:52) ~[corda-node-3.2-corda.jar:?]
    at net.corda.node.services.statemachine.FlowSessionImpl.send(FlowSessionImpl.kt:56) ~[corda-node-3.2-corda.jar:?]
    at com.example.flow.ExampleFlow.sendAMessage(ExampleFlow.java:50) ~[classes/:?]
    at com.example.flow.ExampleFlow.access$000(ExampleFlow.java:11) ~[classes/:?]
    at com.example.flow.ExampleFlow$Initiator.lambda$call$0(ExampleFlow.java:26) ~[classes/:?]
    at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408) ~[guava-21.0.jar:?]
    at com.example.flow.ExampleFlow$Initiator.call(ExampleFlow.java:26) ~[classes/:?]
    at com.example.flow.ExampleFlow$Initiator.call(ExampleFlow.java:12) ~[classes/:?]
    at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:96) [corda-node-3.2-corda.jar:?]
    at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:44) [corda-node-3.2-corda.jar:?]
    at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1092) [quasar-core-0.7.9-jdk8.jar:0.7.9]
    at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:788) [quasar-core-0.7.9-jdk8.jar:0.7.9]
    at co.paralleluniverse.fibers.RunnableFiberTask.doExec(RunnableFiberTask.java:100) [quasar-core-0.7.9-jdk8.jar:0.7.9]
    at co.paralleluniverse.fibers.RunnableFiberTask.run(RunnableFiberTask.java:91) [quasar-core-0.7.9-jdk8.jar:0.7.9]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_171]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_171]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
    at net.corda.node.utilities.AffinityExecutor$ServiceAffinityExecutor$1$thread$1.run(AffinityExecutor.kt:62) [corda-node-3.2-corda.jar:?]
[WARN ] 17:03:28,364 [Mock network] (StateMachineManagerImpl.kt:79) flow.[0f10b2ef-f456-4e28-9998-1b2a403c6caf].uncaughtException - Caught exception from flow {}
java.lang.IllegalStateException: Was expecting to find transaction set on current strand: Fiber@10000001:[0f10b2ef-f456-4e28-9998-1b2a403c6caf][task: co.paralleluniverse.fibers.RunnableFiberTask@12a75b63(Fiber@10000001), target: null, scheduler: net.corda.node.services.statemachine.StateMachineManagerImpl$FiberScheduler@3facca05]
    at net.corda.nodeapi.internal.persistence.DatabaseTransactionKt.getContextTransaction(DatabaseTransaction.kt:14) ~[corda-node-api-3.2-corda.jar:?]
    at net.corda.node.services.statemachine.FlowStateMachineImpl.rollbackTransaction$node(FlowStateMachineImpl.kt:151) ~[corda-node-3.2-corda.jar:?]
    at net.corda.node.services.statemachine.StateMachineManagerImpl$initFiber$3.invoke(StateMachineManagerImpl.kt:460) ~[corda-node-3.2-corda.jar:?]
    at net.corda.node.services.statemachine.StateMachineManagerImpl$initFiber$3.invoke(StateMachineManagerImpl.kt:63) ~[corda-node-3.2-corda.jar:?]
    at net.corda.node.services.statemachine.FlowStateMachineImpl.processException(FlowStateMachineImpl.kt:131) ~[corda-node-3.2-corda.jar:?]
    at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:112) ~[corda-node-3.2-corda.jar:?]
    at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:44) ~[corda-node-3.2-corda.jar:?]
    at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1092) [quasar-core-0.7.9-jdk8.jar:0.7.9]
    at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:788) [quasar-core-0.7.9-jdk8.jar:0.7.9]
    at co.paralleluniverse.fibers.RunnableFiberTask.doExec(RunnableFiberTask.java:100) [quasar-core-0.7.9-jdk8.jar:0.7.9]
    at co.paralleluniverse.fibers.RunnableFiberTask.run(RunnableFiberTask.java:91) [quasar-core-0.7.9-jdk8.jar:0.7.9]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_171]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_171]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
    at net.corda.node.utilities.AffinityExecutor$ServiceAffinityExecutor$1$thread$1.run(AffinityExecutor.kt:62) [corda-node-3.2-corda.jar:?]
```

**Comment by manishchainThat** [comment] 2018-08-07 18:42
From error log ,I believe there is no transaction involved in this flow.I think

**Comment by joeldudleyr3** [comment] 2018-08-08 16:36
See https://r3-cev.atlassian.net/browse/CORDA-1882.

**Comment by manishchainThat** [comment] 2018-08-08 17:54
see this for the solution : 
https://stackoverflow.com/questions/50638968/in-corda-unexpected-task-state-when-running-a-flow?rq=1

**Comment by ekudel** [comment] 2018-10-17 13:18
@joeldudleyr3 Hi. I've faced with it, but I don't have any lambda around, so I can't find a workaround :( Here's my full stacktrace

`java.lang.NullPointerException:` null
	at net.corda.node.services.statemachine.FlowStateMachineImpl.suspend(FlowStateMachineImpl.kt:514) ~[corda-node-3.2-corda.jar:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.sendInternal(FlowStateMachineImpl.kt:370) ~[corda-node-3.2-corda.jar:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.initiateSession(FlowStateMachineImpl.kt:434) ~[corda-node-3.2-corda.jar:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.sendAndReceive(FlowStateMachineImpl.kt:198) ~[corda-node-3.2-corda.jar:?]
	at net.corda.node.services.statemachine.FlowSessionImpl.sendAndReceive(FlowSessionImpl.kt:29) ~[corda-node-3.2-corda.jar:?]
	at net.corda.node.services.statemachine.FlowSessionImpl.sendAndReceive(FlowSessionImpl.kt:40) ~[corda-node-3.2-corda.jar:?]
	at net.corda.core.flows.DataVendingFlow.sendPayloadAndReceiveDataRequest(SendTransactionFlow.kt:70) ~[corda-core-3.2-corda.jar:?]
	at net.corda.core.flows.DataVendingFlow.call(SendTransactionFlow.kt:48) ~[corda-core-3.2-corda.jar:?]
	at net.corda.core.flows.DataVendingFlow.call(SendTransactionFlow.kt:31) ~[corda-core-3.2-corda.jar:?]
	at net.corda.core.flows.FlowLogic.subFlow(FlowLogic.kt:290) ~[corda-core-3.2-corda.jar:?]
	at net.corda.core.flows.FinalityFlow.call(FinalityFlow.kt:63) ~[corda-core-3.2-corda.jar:?]
	at net.corda.core.flows.FinalityFlow.call(FinalityFlow.kt:28) ~[corda-core-3.2-corda.jar:?]
	at net.corda.core.flows.FlowLogic.subFlow(FlowLogic.kt:290) ~[corda-core-3.2-corda.jar:?]
	at com.fluyd.corda.issuer.flows.ProcessNostroTransactionsFlow.performCashIssuing(ProcessNostroTransactionsFlow.kt:106) ~[classes/:?]
	at com.fluyd.corda.issuer.flows.ProcessNostroTransactionsFlow.performUpdateStatesFlow(ProcessNostroTransactionsFlow.kt:92) ~[classes/:?]
	at com.fluyd.corda.issuer.flows.ProcessNostroTransactionsFlow.call(ProcessNostroTransactionsFlow.kt:71) ~[classes/:?]
	at com.fluyd.corda.issuer.flows.ProcessNostroTransactionsFlow.call(ProcessNostroTransactionsFlow.kt:35) ~[classes/:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:96) [corda-node-3.2-corda.jar:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:44) [corda-node-3.2-corda.jar:?]
	at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1092) [quasar-core-0.7.9-jdk8.jar:0.7.9]
	at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:788) [quasar-core-0.7.9-jdk8.jar:0.7.9]
	at co.paralleluniverse.fibers.RunnableFiberTask.doExec(RunnableFiberTask.java:100) [quasar-core-0.7.9-jdk8.jar:0.7.9]
	at co.paralleluniverse.fibers.RunnableFiberTask.run(RunnableFiberTask.java:91) [quasar-core-0.7.9-jdk8.jar:0.7.9]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]`

**Comment by lolo8304** [comment] 2019-01-09 22:21
Hi @ekudel 
I had the same issue and I even used an example cordapp. The problem is that it does not work in a pure java project.

Solution / better workaround:
- create a kotlin project - even without developing kotlin. And then it works. 
- I was debugging for 3 days and then stripped it down to "java" vs "kotlin" module with 100% the same "java code". 
- kotlin: worked, java: nullpointer

**Comment by lolo8304** [comment] 2019-01-09 22:34
another info: the bug seems to be very deep down because the jvm did non even stop on "ctrl-c" or "kill <id>". I had to use "kill -9 <id>"

**Comment by lolo8304** [comment] 2019-01-12 14:41
@ekudel  - i tried to setup a new "project" with kotlin but code in java and 1 flow to reproduce.
and I have the same issue again. I am running 1 project which is working and one which is not working.
SHIT - i tried to compare now file by file

**Comment by lolo8304** [comment] 2019-01-12 23:45
Solution
- create a kotlin based project
- add packages with the "SAME NAME" as the kotlin packages in src/main/java
- and create classes


if you use kotlin packages name com.a.b and java packages ch.c.d then the flow can be started but while counter-sign it crashes with NullPointecxeption

I have created a an example to download ...

**test that works**
```
flow start com.prototypes.insurance.iou.flows.ExampleFlow iouValue: 30, otherParty: PartyB 
flow start com.prototypes.whistleblower.BlowWhistleFlow badCompany: PartyB, investigator: PartyB
```
![test ok](https://user-images.githubusercontent.com/5243791/51079719-40559200-16cc-11e9-9f90-36149906bfca.png)


**test that fails**
`flow starts ch.insurance.cordapp.broker.flows.ExampleFlow iouValue: 30, otherParty: PartyB
`
![test not-ok](https://user-images.githubusercontent.com/5243791/51079724-56635280-16cc-11e9-9fd9-ccf23ca3b2f2.png)

test cordapp-source
[insurance-cordappK.zip](https://github.com/corda/corda/files/2752655/insurance-cordappK.zip)

**Comment by keykey7** [comment] 2019-03-19 13:21
I also face NPEs on a pure-java dapp during the suspend.
```
java.lang.NullPointerException
	at net.corda.node.services.statemachine.FlowStateMachineImpl.suspend(FlowStateMachineImpl.kt:380)
	at net.corda.node.services.statemachine.FlowSessionImpl.send(FlowSessionImpl.kt:78)
	at net.corda.node.services.statemachine.FlowSessionImpl.send(FlowSessionImpl.kt:82)
```
It's not the first suspend within this flow. I can only reproduce it on a real multinode setup, but not with a multinode mock network. `-Dco.paralleluniverse.fibers.verifyInstrumentation=true` doesn't complain nor does `flowStackSnapshot()` reveal any unexpected insights: there are no lambdas, unserializable classes, or alike in any frame. @lolo8304's kotlin-project-hack didn't help either.
Any ideas on how to further debug such a Fiber issue?

**Comment by keykey7** [comment] 2019-04-09 14:14
In our case the issue was fixed by https://github.com/corda/corda/pull/4808 -> packages starting with 'ch' were explicitly excluded. I see @lolo8304 also mentioning a package name "ch.c.d": this might be related as well.

**Comment by davidrapacchiale** [comment] 2020-05-20 09:27
Closing this issue as it is related to an old version of the software. Either not relevant any longer, or fixed elsewhere. Please do reopen if still relevant.

**Closed by davidrapacchiale** 2020-05-20 09:27 UTC
Labels: bug
