### ISSUE TITLE
Certain map operations causing un-restorable flow checkpoints

### ISSUE THREAD

**Issue by roger3cev** [corda/corda#1869] opened 2017-10-11 14:32 UTC
For example:

`dataStore.status.filterValues { value -> value == DetectState.RequestStatus.ACKNOWLEDGED }.keys`

which produces `LinkedHashMap.EntryKeySet`s and it appears they are not serialisable.

Cheers

**Comment by balajimore** [comment] 2017-11-07 07:01
As HashMap is blocked, so I used LinkedHashMap but then also it is throwing error on serialization. Please check and take this issue on priority.

`        @Suspendable
        override fun call() {
            //receive document from customer
            val docsJarMap = customerFlowSession.receive<Map<UniqueIdentifier, ByteArray>>().unwrap { it ->
                it
            }

            //upload the document and store hash of it.
            val docsAndHash: MutableMap<UniqueIdentifier, SecureHash> = LinkedHashMap()
            docsJarMap.entries.forEach {
                val docHash = serviceHub.attachments.importAttachment(it.value.inputStream())
                docsAndHash.put(it.key, docHash)
            }

            //send document linearId and hash
            customerFlowSession.send(docsAndHash)
        }`


**StackTrace:**

`[ERROR] 12:27:34,596 [pool-22-thread-1] (StateMachineManager.kt:432) flow.[ab776b0f-fab3-4ef9-8317-68f487596d53].deserializeFiber - Encountered unrestorable checkpoint!
com.esotericsoftware.kryo.KryoException: java.lang.UnsupportedOperationException
Serialization trace:
dataObject (co.paralleluniverse.fibers.Stack)
stack (net.corda.node.services.statemachine.FlowStateMachineImpl)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:144) ~[kryo-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer.read(CompatibleFieldSerializer.java:147) ~[kryo-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.readObjectOrNull(Kryo.java:782) ~[kryo-4.0.0.jar:?]
	at co.paralleluniverse.io.serialization.kryo.ReplaceableObjectKryo.readObjectOrNull(ReplaceableObjectKryo.java:107) ~[quasar-core-0.7.9-jdk8.jar:0.7.9]
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:132) ~[kryo-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:540) ~[kryo-4.0.0.jar:?]
	at co.paralleluniverse.fibers.Fiber$FiberSerializer.read(Fiber.java:2137) ~[quasar-core-0.7.9-jdk8.jar:0.7.9]
	at co.paralleluniverse.fibers.Fiber$FiberSerializer.read(Fiber.java:2067) ~[quasar-core-0.7.9-jdk8.jar:0.7.9]
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813) ~[kryo-4.0.0.jar:?]
	at co.paralleluniverse.io.serialization.kryo.ReplaceableObjectKryo.readClassAndObject(ReplaceableObjectKryo.java:112) ~[quasar-core-0.7.9-jdk8.jar:0.7.9]
	at net.corda.nodeapi.internal.serialization.AbstractKryoSerializationScheme$deserialize$$inlined$use$lambda$1$1.invoke(SerializationScheme.kt:209) ~[corda-node-api-1.0.0.jar:?]
	at net.corda.nodeapi.internal.serialization.AbstractKryoSerializationScheme$deserialize$$inlined$use$lambda$1$1.invoke(SerializationScheme.kt:152) ~[corda-node-api-1.0.0.jar:?]
	at net.corda.nodeapi.internal.serialization.AbstractKryoSerializationScheme.withContext(SerializationScheme.kt:191) ~[corda-node-api-1.0.0.jar:?]
	at net.corda.nodeapi.internal.serialization.AbstractKryoSerializationScheme.access$withContext(SerializationScheme.kt:152) ~[corda-node-api-1.0.0.jar:?]
	at net.corda.nodeapi.internal.serialization.AbstractKryoSerializationScheme$deserialize$$inlined$use$lambda$1.execute(SerializationScheme.kt:206) ~[corda-node-api-1.0.0.jar:?]
	at com.esotericsoftware.kryo.pool.KryoPoolQueueImpl.run(KryoPoolQueueImpl.java:61) ~[kryo-4.0.0.jar:?]
	at net.corda.nodeapi.internal.serialization.AbstractKryoSerializationScheme.deserialize(SerializationScheme.kt:205) ~[corda-node-api-1.0.0.jar:?]
	at net.corda.nodeapi.internal.serialization.SerializationFactoryImpl$deserialize$1$1.invoke(SerializationScheme.kt:115) ~[corda-node-api-1.0.0.jar:?]
	at net.corda.core.serialization.SerializationFactory.withCurrentContext(SerializationAPI.kt:53) ~[corda-core-1.0.0.jar:?]
	at net.corda.nodeapi.internal.serialization.SerializationFactoryImpl$deserialize$1.invoke(SerializationScheme.kt:115) ~[corda-node-api-1.0.0.jar:?]
	at net.corda.nodeapi.internal.serialization.SerializationFactoryImpl$deserialize$1.invoke(SerializationScheme.kt:95) ~[corda-node-api-1.0.0.jar:?]
	at net.corda.core.serialization.SerializationFactory.asCurrent(SerializationAPI.kt:67) ~[corda-core-1.0.0.jar:?]
	at net.corda.nodeapi.internal.serialization.SerializationFactoryImpl.deserialize(SerializationScheme.kt:115) ~[corda-node-api-1.0.0.jar:?]
	at net.corda.testing.TestSerializationFactory.deserialize(SerializationTestHelpers.kt:104) ~[corda-test-utils-1.0.0.jar:?]
	at net.corda.node.services.statemachine.StateMachineManager.deserializeFiber(StateMachineManager.kt:708) [corda-node-1.0.0.jar:?]
	at net.corda.node.services.statemachine.StateMachineManager.access$deserializeFiber(StateMachineManager.kt:78) [corda-node-1.0.0.jar:?]
	at net.corda.node.services.statemachine.StateMachineManager$updateCheckpoint$2.run(StateMachineManager.kt:562) [corda-node-1.0.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.UnsupportedOperationException
	at java.util.AbstractCollection.add(AbstractCollection.java:262) ~[?:1.8.0_131]
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:134) ~[kryo-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40) ~[kryo-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731) ~[kryo-4.0.0.jar:?]
	at co.paralleluniverse.io.serialization.kryo.ReplaceableObjectKryo.readObject(ReplaceableObjectKryo.java:92) ~[quasar-core-0.7.9-jdk8.jar:0.7.9]
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:392) ~[kryo-4.0.0.jar:?]
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:303) ~[kryo-4.0.0.jar:?]
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731) ~[kryo-4.0.0.jar:?]
	at co.paralleluniverse.io.serialization.kryo.ReplaceableObjectKryo.readObject(ReplaceableObjectKryo.java:92) ~[quasar-core-0.7.9-jdk8.jar:0.7.9]
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125) ~[kryo-4.0.0.jar:?]
	... 29 more

java.lang.IllegalStateException: Check failed.

	at net.corda.testing.node.InMemoryMessagingNetwork$InMemoryMessaging.pumpReceive(InMemoryMessagingNetwork.kt:399)
	at net.corda.testing.node.MockNetwork$runNetwork$1.invoke(MockNode.kt:363)
	at net.corda.testing.node.MockNetwork.runNetwork(MockNode.kt:366)
	at net.corda.testing.node.MockNetwork.runNetwork$default(MockNode.kt:361)
	at com.leia.base.DocumentHandlerTests.Send documents to counter party(DocumentHandlerTests.kt:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


java.lang.IllegalStateException: Unrestorable checkpoints where created, please check the logs for details.

	at net.corda.node.services.statemachine.StateMachineManager.stop(StateMachineManager.kt:228)
	at net.corda.node.internal.AbstractNode$start$$inlined$apply$lambda$1$1.invoke(AbstractNode.kt:225)
	at net.corda.node.internal.AbstractNode$start$$inlined$apply$lambda$1$1.invoke(AbstractNode.kt:98)
	at net.corda.node.internal.AbstractNode.stop(AbstractNode.kt:620)
	at net.corda.node.internal.StartedNode$DefaultImpls.dispose(StartedNode.kt:25)
	at net.corda.node.internal.AbstractNode$StartedNodeImpl.dispose(AbstractNode.kt:102)
	at net.corda.testing.node.MockNetwork.stopNodes(MockNode.kt:446)

`

**Comment by mikehearn** [comment] 2017-11-15 17:38
Can you move the calculation of the map into a private function and see if that works? 

BTW, response time on github tickets is not guaranteed. You may wish to use our commercial support option: https://www.corda.net/support/

**Comment by joeldudleyr3** [comment] 2018-11-13 09:34
@balajimore  I'm closing this for now. If you can replicate this issue on Corda 3 or above, would you be able to re-open an issue?

**Closed by joeldudleyr3** 2018-11-13 09:34 UTC
Labels: bug

**Comment by Pris17** [comment] 2020-08-18 11:38
I am facing this issue. Can somebody give the solution to this?

**Comment by mnesbit** [comment] 2020-08-18 11:42
Upgrade to Corda 4.5, which has fixed deserialization issues with Map iterators

**Comment by Pris17** [comment] 2020-08-18 14:34
Ok, Thanks. Can this issue occur because of low RAM memory?

**Comment by Pris17** [comment] 2020-08-21 13:35
Upgrading to 4.5 didn't resolve the issue. Below are the more details of the error and the flow execution.

Flow execution is between account A on Node A and the responder are 2 members i.e. account B on Node B and Node C is executing successfully, but it throws the tones of warnings and the error related to FiberDeserializationChecker at the end of flow execution.
```
[ERROR] 13:42:00+0530 [FiberDeserializationChecker] interceptors.FiberDeserializationChecker. - Encountered unrestorable checkpoint! - java.lang.NullPointerException
Serialization trace:
childProgressTrackers (net.corda.core.utilities.ProgressTracker)
progressTracker (com.blockchain.corda.flows.initiator.UpdateInitiatorFlow)
this$0 (com.blockchain.corda.flows.initiator.UpdateInitiatorFlow$2)
second (kotlin.Pair)_allStepsCache (net.corda.core.utilities.ProgressTracker)
progressTracker(com.lti.blockchain.corda.flows.initiator.CreateInitiatorFlow)logic (net.corda.node.services.statemachine.FlowStateMachineImpl) [errorCode=7sftly, moreInformationAt=https://errors.corda.net/OS/4.5/7sftly]
```
Flow execution is as follows:
Triggers the CreateInitiatorFlow, this will create the state as per the logic.
On successful creation of the state, we are calling the sub-flow i.e UpdateInitiatorFlow, which will update few details in another state.
After the successful execution of sub-flow, it returns back to the main flow and returns the response but with the above error.

How to resolve this?
