### ISSUE TITLE
Apparent classpath conflict with Apache Commons Collections in 3.1

### ISSUE THREAD

**Issue by joeldudleyr3** [corda/corda#3132] opened 2018-05-14 09:06 UTC
See https://stackoverflow.com/questions/50313622/java-lang-noclassdeffounderror-org-apache-commons-collections4-map-lrumap-when.

This is on a clean clone of CorDapp Example 3.1 (https://github.com/corda/cordapp-example). The CorDapp Example uses `org.apache.commons.collections4-4.1`. This dependency was added by this commit: https://github.com/corda/corda/commit/04d8260e0fd3e68c1ffe79d761989a5b324e47fb, in October 2017.

**Comment by joeldudleyr3** [comment] 2018-05-14 09:10
Being tracked here: https://r3-cev.atlassian.net/browse/CORDA-1473.

**Comment by clydedacruz** [comment] 2018-05-14 11:55
Just noticed ... it doesn't seem to appear with Java 1.8.0_162-b12

**Comment by joeldudleyr3** [comment] 2018-05-14 15:59
Thanks for the information. Bugs are triaged on Tuesdays :)

**Comment by mikehearn** [comment] 2018-10-04 16:58
Going to close this - we can't reproduce it. That repo is also deprecated and we've updated the examples since.

**Closed by mikehearn** 2018-10-04 16:58 UTC
Labels: bug
