### ISSUE TITLE
Corda network builder link gives  404 error

### ISSUE THREAD

**Issue by karthik137** [corda/corda#5750] opened 2019-11-21 05:45 UTC
### Description

Unable to access corda network builder snapshot. corda-tools-network-builder-4.3-SNAPSHOT.jar is missing.

### Steps to reproduce the issue

1) Go to https://docs.corda.net/network-builder.html
2) Click 'Download the Corda Network Builder'.
3) Browser gives error message -->

```
{
  "errors" : [ {
    "status" : 404,
    "message" : "{\"error\":\"Item corda-releases:net/corda/corda-tools-network-builder/4.3-SNAPSHOT does not exist\"}"
  } ]
}
```

### What is missing?

i think 4.3-SNAPSHOT directory is missing.
Please check this link -->

https://ci-artifactory.corda.r3cev.com/artifactory/corda-releases/net/corda/corda-tools-network-builder/4.3-SNAPSHOT/

### Corda version 

4.3

**Comment by opticyclic** [comment] 2019-11-27 20:00
This is a duplicate of this[ other issue](https://github.com/corda/corda/issues/4233) from Nov 2018!

**Comment by davidrapacchiale** [comment] 2020-01-21 10:05
Closed as dupe of above issue. We will comment on the other one and file a bug on our OS Jira project

**Closed as completed by davidrapacchiale** 2020-01-21 10:05 UTC
Labels: bug, Triaged
