### ISSUE TITLE
Would you guys support a Node SDK?

### ISSUE THREAD

**Issue by opiepj** [corda/corda#823] opened 2017-06-08 18:11 UTC
Any plans to provide Node.js bindings?

**Comment by mikehearn** [comment] 2017-06-08 18:33
No announced plans at this time for nodejs. Note that you can use JavaScript on the JVM and if you take a look here:

http://www.oracle.com/technetwork/oracle-labs/program-languages/overview/index-2301583.html

.... there's a JVM that claims to be NodeJS compatible and which runs code as fast as V8. I haven't tested it out myself but I know the same tech can run Ruby pretty well.  It'd be interesting to know how node.js compatible it really is.

We do have plans to support non-JVM runtimes in the longer term, at least for RPC, but we'll probably start with C# / .NET

I'll close this issue now as we use JIRA for tracking features and each separate runtime would be its own feature story.

**Closed by mikehearn** 2017-06-08 18:33 UTC

**Comment by opiepj** [comment] 2017-06-09 20:53
What about WASM ;)

**Comment by mikehearn** [comment] 2017-06-12 09:21
Nope :)

**Comment by urbien** [comment] 2018-01-30 19:36
+1 for nodejs support by having JS SDK or via wasm  / webassembly

**Comment by urbien** [comment] 2018-02-01 03:31
ok, we decided to use this path nodeja -> Jetty -> RPC to CorDApp
@mikehearn would be great if you or someone on the team confirmed it is kosher and what pitfalls to avoid. 

1. Our nodejs app (running in AWS Lambda) will issue a REST request to our servlet in deployed in Jetty on Corda node. 
2. The servlet will proxy a request to RPC CorDApp.
3. We will obviously need to install SSL cert on Jetty and define some API key.

Thoughts?

**Comment by opiepj** [comment] 2018-02-06 18:24
@urbien wasn't serious about WASM

Wonder if it would be possible to create C bindings for Corda that way you scale out to other ecosystems. I couldn't imagine how much of an overhaul that would be at this point

**Comment by arsalankhalid** [comment] 2019-02-01 06:30
Why in your opinion would C bindings facilitate faster scale to ecosystems?

**Comment by mikehearn** [comment] 2019-02-05 14:34
@urbien That approach works, but also look at SubstrateVM, which can give instant startup and low memory usage for Java apps that meet certain requirements:

https://royvanrijn.com/blog/2018/09/part-2-native-microservice-in-graalvm/

I don't know if our RPC works in SubstrateVM, I suspect it can do if you pin enough classes for reflection.

W.R.T. JavaScript bindings, I demoed a thing called "corda.js" at CordaCon which is using GraalVM's NodeJS/Java interop. You can find the video on YouTube. It's not that hard to replicate.

But generally I'm not sure that running high level languages in an AWS Lambda type environment is going to be efficient. Any language higher level than C will benefit from a speculating JIT compiler, that definitely includes JavaScript, but having the process be constantly torn down and rebuilt just wipes the JITC memory over and over. Node/V8 doesn't do anything magical there, it's just optimised for startup time because it does less, but you'll still be getting worse performance out of it rather than letting it warm up.

W.R.T. WASM, one of the things I plan to experiment with is LLVM/C interop using - again - GraalVM. So whilst WASM bytecode itself is currently a nope, LLVM bitcode interop with RPC *is* possible.

Finally, since I last commented on this issue, I've written the start of C++ bindings for the protocol. The aim is for embedded use cases.

**Comment by urbien** [comment] 2019-02-06 13:16
@mikehearn thank you for your response!
As discussed with you at CordaCon in Tokyo I do not think it is an issue anymore for us. We have created a workaround with a servlet that is being pinged from Lambda (I will ask @mvayngrib to give you a specific setup). I think you said in Tokyo that you have a better environment for such servlets. 

Re: Java in Lambda. The key problem is the cold start. [Java is 10x worse than JS](https://epsagon.com/blog/aws-lambda-programming-language-comparison/). 

I agree in theory with your JIT argument, but in reality, Java Applets always took time to start in the browser, compared to JS, which was one of the reasons we do no run Java in the browser anymore. Lambda (and Azure function, and Google functions) create that same requirement for a quick start. Maybe things will improve with AWS custom runtimes, no benchmarks yet as far as I know, but I would not bet on it. 
Anyway, a servlet as a proxy to Corda works fine. The key is for the servlet to be hosted by the Corda node. This will allow our solution to remain serverless.
