### ISSUE TITLE
Banks can only issue one currency

### ISSUE THREAD

**Issue by scottejames** [corda/corda#754] opened 2017-05-26 15:19 UTC
Not sure if this is a bug or a feature.  If you create a bank that can issue multiple currencies.   If you actually try and issue a currency from the transaction screen of the explorer only the first currency is available.  This happens no matter what permutation of currencies you enable, you can only select the first.

<img width="297" alt="screen shot 2017-05-26 at 4 18 12 pm" src="https://cloud.githubusercontent.com/assets/775585/26500739/077b1680-422f-11e7-944a-2d8dcfa3c5b2.png">
<img width="475" alt="screen shot 2017-05-26 at 4 18 29 pm" src="https://cloud.githubusercontent.com/assets/775585/26500750/0c3549c0-422f-11e7-82a7-7060318f53c4.png">
<img width="523" alt="screen shot 2017-05-26 at 4 18 50 pm" src="https://cloud.githubusercontent.com/assets/775585/26500756/0ff02184-422f-11e7-851a-e49e710e616b.png">

**Comment by mikehearn** [comment] 2017-05-26 15:58
Thanks for the report Scott. This is a duplicate of #567

**Closed by mikehearn** 2017-05-26 15:58 UTC
