### ISSUE TITLE
Vault query fails to find a state if it extends from class

### ISSUE THREAD

**Issue by Alex-Koller** [corda/corda#3714] opened 2018-07-29 10:46 UTC
Hi

My state (S) extends from class (C), which in turn implements interface (I).

I.e. S -> C -> I

If I use this query: 

`vaultService.queryBy<I>()`

Where "I" is my interface the query will *not* return state S, although it exists in the vault. I believe the problem is in the method _deriveContractInterfaces_ in class NodeVaultService, which should perhaps traverse up in the hierarchy, not just look at the immediate interfaces the class implements.

I'm observing this behavior on 3.2

**Comment by lankydan** [comment] 2018-07-29 17:03
Just jumping in here. Not sure how easy/possible this would be to do. The `vault_states` table saves the immediate type of a state when saving to the database. The query searches for records in the table which match the type passed into the query. To pass in an interface instead, would require the classpath to be scanned for the types that implement an interface or extend a class.

At the end of the day this depends on the time it takes to scan the classpath for this data. I can see that in some parts of the codebase `fast-classpath-scanner` has been imported. If this is fast enough to scan for subtypes when setting up each query, then this is a possible solution, but I don't have any experience with how long classpath scanning takes.

It could be possible to store type information about states at startup and check against this when each query criteria is constructed. This could be done by retrieving all types from a list of states that extend a class/interface (using `is`) and instead of the current query criteria, use an `OR` for the `contractStateClassName` field for each valid type from the list.

Anyway, thats what I think 😄

**Comment by Alex-Koller** [comment] 2018-07-29 18:33
Given that when I take the class C out of the picture and have S implement I the query works as expected, and looking at the underlying code, I think the query is *intended* to work when interfaces are passed in. And I'm finding it quite useful. But it only works when the state in question implements the interface immediately, without anything in between. And that I'm not so sure is intended behavior.

**Comment by lankydan** [comment] 2018-07-29 18:42
ah, cool. I missed that, after looking at the code a bit more it looks like you right. The implementation already does some of what I mentioned earlier but does look like it only uses the interfaces like you described.

Maybe something can be done about it then 👍

**Comment by joeldudleyr3** [comment] 2018-07-30 08:32
Thanks. Raised as an issue here: https://r3-cev.atlassian.net/browse/CORDA-1858.

**Comment by josecoll** [comment] 2018-07-30 14:11
@Alex-Koller I'm not sure I can reproduce your problem exactly as you have explained it.

```
    open class BaseState(override val participants: List<AbstractParty> = emptyList()) : ContractState
    data class MyState(val name: String, override val participants: List<AbstractParty> = emptyList()) : BaseState(participants)
```
Upon recording a single State of type `MyState`, I note the following query outcome:
- using the child class ``vaultService.queryBy<MyState>(criteria)`` succeeds
- using the parent class ``vaultService.queryBy<BaseState>(criteria)`` fails   (**this should succeed and is indeed a bug**)
- using the interface ``vaultService.queryBy<ContractState>(criteria)`` succeeds
In your description you mention the query by Interface fails ^^^

Please can you provide a concrete example. Many thanks.

**Comment by Alex-Koller** [comment] 2018-07-30 14:29
Hi, thanks for the quick turnaround. If I'm not mistaken querying by ContractState is treated specifically in the code. Try instead of ContractState implement a custom Interface first. In my example I had:

`interface InterestRateDerivative : LinearState`

 `abstract class State() : InterestRateDerivative {
 }`

 `data class CapState() : State {
  }`

This, of course, won't compile due to missing abstract properties but is the hierarchy that didn't work for me. If you still can't reproduce it I will dig out and post my code.

**Comment by josecoll** [comment] 2018-07-31 16:18
Addressed in PR https://github.com/corda/corda/pull/3722

**Comment by josecoll** [comment] 2018-07-31 16:18
@Alex-Koller please confirm the fix works for you. Thanks.

**Comment by manishchainThat** [comment] 2018-11-14 13:56
@josecoll   it worked for me . Thanks

**Closed** 2018-11-14 13:59 UTC
