### ISSUE TITLE
irs-demo.bat not working

### ISSUE THREAD

**Issue by seelemonsonline** [corda/corda#103] opened 2017-01-03 22:08 UTC
(Very low low priority issue)

When running "irs-demo.bat --role UploadRates" I get the output:

C:\Users\cleme\Documents\_Dev\corda\corda\samples\irs-demo\build\install\irs-demo\bin>irs-demo.bat --role UploadRates
The input line is too long.
The syntax of the command is incorrect.

I was able to switch back to gitbash and run ./irs-demo --role UploadRates successfully

**Comment by Clintonio** [comment] 2017-01-04 11:05
I have reproduced this issue on my local machine and the issue appears to be a limitation of Microsoft's command line. Thank you for the report.

**Comment by Clintonio** [comment] 2017-01-04 11:09
The related issue in Gradle's github: https://github.com/gradle/gradle/issues/1064

Looks like we're going to need to replace application distribution plugin for M7.

**Comment by mikehearn** [comment] 2017-01-04 11:42
Yes Win32 API imposes hard length limits on command lines (actually UNIX used to have this same issue).

However we could all benefit on every platform from having short classpaths. We should not have any dependencies on classpath ordering (if we do it's a bug!) and so using wildcards in the classpath should work great. I don't know if the application plugin knows how to generate wildcard classpaths but maybe we can override the classpath it uses with a hand-written one.

BTW the irs-demo.bat file will go away in future I hope, in favour of the RPC command line tool.

**Comment by Clintonio** [comment] 2017-01-04 11:45
@mikehearn You can replace it with a wildcard. I've fixed it for Windows so far in my branch but I'll see about making it work for all platforms.

**Comment by Clintonio** [comment] 2017-01-05 14:25
Fixed in PR #104.

**Closed by Clintonio** 2017-01-05 14:25 UTC
