### ISSUE TITLE
Some machines have incorrect local routing tables, need workarounds

### ISSUE THREAD

**Issue by wawrzek** [corda/corda#280] opened 2017-02-23 15:16 UTC
Corda insists to to bind (I believe Artemis) to the interface with public hostname/IP address. This doesn't necessary equal IP address visible in the internet. Actually, in cloud (Azure for sure) it's not equal.

```[INFO ] 2017-02-23T10:33:22,238 [main] messaging.NodeMessagingClient.start - Connecting to server: cordatest1-node1.corda.r3cev.com:10002
[ERROR] 2017-02-23T10:33:52,544 [main] Main.main - Exception during node startup
org.apache.activemq.artemis.api.core.ActiveMQNotConnectedException: AMQ119007: Cannot connect to server(s). Tried with all available servers.
        at org.apache.activemq.artemis.core.client.impl.ServerLocatorImpl.createSessionFactory(ServerLocatorImpl.java:785) ~[artemis-core-client-1.5.1.jar:1.5.1]
        at net.corda.node.services.messaging.NodeMessagingClient.start(NodeMessagingClient.kt:127) ~[node-0.9-SNAPSHOT.jar:?]
        at net.corda.node.internal.Node.startMessagingService(Node.kt:151) ~[node-0.9-SNAPSHOT.jar:?]
        at net.corda.node.internal.AbstractNode$start$3.invoke(AbstractNode.kt:263) ~[node-0.9-SNAPSHOT.jar:?]
        at net.corda.node.internal.AbstractNode$start$3.invoke(AbstractNode.kt:75) ~[node-0.9-SNAPSHOT.jar:?]
        at net.corda.node.internal.AbstractNode$initialiseDatabasePersistence$2.invoke(AbstractNode.kt:321) ~[node-0.9-SNAPSHOT.jar:?]
        at net.corda.node.internal.AbstractNode$initialiseDatabasePersistence$2.invoke(AbstractNode.kt:75) ~[node-0.9-SNAPSHOT.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:69) ~[exposed-0.5.0.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:57) ~[exposed-0.5.0.jar:?]
        at net.corda.node.utilities.DatabaseSupportKt.databaseTransaction(DatabaseSupport.kt:39) ~[node-0.9-SNAPSHOT.jar:?]
        at net.corda.node.internal.AbstractNode.initialiseDatabasePersistence(AbstractNode.kt:320) ~[node-0.9-SNAPSHOT.jar:?]
        at net.corda.node.internal.Node.initialiseDatabasePersistence(Node.kt:201) ~[node-0.9-SNAPSHOT.jar:?]
        at net.corda.node.internal.AbstractNode.start(AbstractNode.kt:202) ~[node-0.9-SNAPSHOT.jar:?]
        at net.corda.node.internal.Node.start(Node.kt:206) ~[node-0.9-SNAPSHOT.jar:?]
        at net.corda.node.Corda.main(Corda.kt:109) [node-0.9-SNAPSHOT.jar:?]```

**Comment by evilkid** [comment] 2017-02-24 13:30
I can confirm that this exception is triggered when the "artemisAddress" on the node config is set to an IP that is not bound to any of the network interfaces (which is sane enough) like an external public IP address.
But this external IP address needs to be somehow visible to the network manager in order to communicate with the Node, in case these 2 weren't in the same network. 
I have noticed that during the node registering on the network manager, that the IP/hostname which was written in the node.conf file is used to add this node to the network map: 
`[INFO ] 2017-02-24T13:15:34,032 [Node thread] NetworkMapService - Added node NodeAddress(queueName=internal.peers.bzs7kfCTaPyeW1jSJnQU9NT1D6jJ5bK96485RB8afd6urZdz7r, hostAndPort=**localhost:10004**) to network map`
(Notice the localhost:10004 which is the artemisAddress on the node.conf file).
I believe that there are 2 possible fixes. 

1. Introduce a new attribute in the node.conf file such as "externalArtemisAddress" that holds the public IP/hostname. But this wouldn't be an efficient fix in case that the public IP is changing constantly.

2. The second solution, is to make the network service register the node with the incoming IP connection other than (or along with) the IP written in the artemisAddress in the node.conf

**Comment by mikehearn** [comment] 2017-02-27 09:45
Yes. I'll write up my views on this again, as we had a big argument about this on Slack last week.

This is not a bug in Corda. This is a bug in Azure. When TCP/IP and UNIX were designed, APIs were provided to do basic tasks around IP networking, like opening connections and indeed, finding out what your own connectivity looks like. To find out what IP address is used to contact a remote server you can bind a datagram socket and then query it to learn which adapter was chosen by the TCP/IP stack given local routing rules. This is your effective IP address.

On Azure these APIs are broken and do not work because the kernel is not aware of how packet routing is being done. This is nothing to do with "cloud" as there are plenty of cloud providers that don't have this issue, the example I keep using is Linode because that's where I happen to keep my own servers, but there are plenty of other examples. Azure could easily configure its VMs to know about the public IPs it's been allocated, but it doesn't. Searching Google shows people asking about this on StackOverflow and being told to use services like whatismyipaddress.com, which is hardly a robust solution.

We can and should raise this as a ticket through Azure support. Flaky workarounds to find out "true" IP addresses are often required in consumer networks due to IPv4 exhaustion, but in this case the boxes aren't NATd or sharing IPs and they do have a unique global IP assigned to them ... the kernel just doesn't know what it is. There's no real excuse for that. It's not like IPv4 NAT where the limits are fundamental.

We can also put workarounds and various hacks into Corda. There will have to be several:

1. As evilkid suggests, extend the network map server so the IP address used is the connecting IP and not the self-advertised IP. This isn't really the architecture we want to be heading towards; ideally the network map service becomes more and more stateless over time so e.g. signed static maps can be distributed via a CDN. But for now we'll have to provide this functionality as a workaround for broken hosting setups.

2. Make the network map server do dialback, to avoid people registering nodes that are firewalled. Azure also requires you to manually open ports via their web/cli tools even once a public IP is assigned. Again, it's not clear why require this, because the server OS' are quite capable of managing which ports are open or not by themselves. But opening a port on the VM and forgetting to open it via the web UI is going to be a common mistake, so we need a way to detect that.

The artemisAddress config property probably isn't the right thing to use here. That's intended for more advanced cases where the MQ broker is split out into a separate process or machine, but we don't fully support that yet. We can do automated workarounds for as long as we keep a stateful network map server, but ultimately the real fix for people who wish to host nodes in the cloud is to use machines with properly configured adapters. 

Long term we'll support the ability to split the node across firewall boundaries and other configurations that are needed for corporate setups where a node may also interface with internal infrastructure.

**Comment by wawrzek** [comment] 2017-02-27 10:41
@mikehearn:

1. Machines in cloud perfectly know what routing their is. They just don't know IP address they are visible in Public internet. (I don't think it's any different to every corporate network). You might not like it, but Corda have to work in this environment, because everything else works.
2. Which real big player in Cloud space doesn't have the same private/public IP separation? Examples of recent market data (BTW. I checked AWS and Azure 40-60% or market had such configuration):
- https://www.skyhighnetworks.com/cloud-security-blog/microsoft-azure-closes-iaas-adoption-gap-with-amazon-aws/
- https://www.channele2e.com/2017/02/09/cloud-market-share-2017-amazon-microsoft-ibm-google/)
3. Azure CLI require changes to a network firewall not machines. Of course you can set up another firewall on the machine if you want.

**Comment by mikehearn** [comment] 2017-02-27 10:56
Corporate networks are usually NATd: they have internal IPs because they share their external IPs. And yes, NAT breaks lots of programs. Go look at how many video calling tools, video games, P2P apps etc all break due to NAT. It is an ugly hack which is why IPv6 is being so looked forward to and people who say they want IPv6 NAT get sent frowny faces by developers. It works quite well, all the devices and servers I have get a unique public IPv6 and know what it is, software can find out its own address in the usual way. Internal IPs aren't something that are meant to exist in the IPv6 world.

Now our machines are not NATd. If you look at the workarounds required for Azure (or AWS), they're really awful and obviously not how the internet was designed to work. "Just use checkip.com" isn't something that appears in any RFCs or API specs. So the fact that this is a common problem with the big cloud providers doesn't change anything: it just means they're designed on the assumption that you will use lots of machines that don't need to make outbound connections to the internet, or that when they do, they don't need to know their own address. An assumption that works most of the time but not all the time.

Put more bluntly, having lots of market share doesn't let you rewrite how TCP/IP works, nor does it let you declare that anything that doesn't work around your setup is now "buggy". Azure and AWS could have 95% market share between them and it still wouldn't change that this setup is clearly wrong.

Regardless it's not really worth discussing this further. We can schedule time to add in the various workarounds needed. It is a crying shame that these large hosting providers have such awkward networking setups and that the basics of "i connect to you, you connect to me" STILL don't work right even in 2017 ... but that's software.

**Comment by wawrzek** [comment] 2017-02-27 11:28
Public IP address in cloud is not a part of a VM. It's a separate object you can bind to a network card connected to VM if you want. BTW. Network card in cloud is separated from VM as well, so I can move IP address from one NIC to another. I can also move NIC from one VM to another if I want. Most of the machine in cloud doesn't have external visible IP addresses (and it what customers want). You should  think about cloud public IP address as an entry on a router enabling communication with a machine in an another network. That's perfectly sensible configuration. 

Corda as for today assume that every node is part of one IP namespace, and that's wrong assumption. I agree that they might be a ways to achieve, but that are 'fringes' or enterprise world.

BTW. I remembered discussing IPv6 some years ago and how nice it would be to finally get rid of NATing and have all IP addresses available world wide. Somebody pointed that I shouldn't hope for that - firewall, NATing, internal IP addresses will stay. Thinking about that - I don't the bulb in my daughter room to be visible from the internet (Not even saying about her smart mirror - which is not so far away e.g. https://www.youtube.com/watch?v=sh2EJzplkpM)

**Comment by mikehearn** [comment] 2017-02-27 12:16
Yeah, I do understand why they have such a complicated setup. Such services are optimised for the web servers with backend services use case where this problem will not arise and where they wish to use IPv4 as their primary protocol, so they need to aggressively over-commit private IPv4 address space. I wouldn't say customers "want" internal IP ranges exactly - it is just a requirement for IPv4. Certainly it can create potential for confusion that does not exist with global addressing.

Still, peer to peer networks are not that unusual - email, IRC, NNTP, Bitcoin, Ethereum, probably Fabric too I assume. They all assume nodes that can discover and connect to each other. So for such applications they need public IPs. I wonder what happens if you try to run a Bitcoin network entirely on Azure for instance ... how would any peer know how to connect to any other? At that point, requiring extra cloud-specific steps or workarounds like STUN/checkip.com style servers is obviously a problem, the internet was never designed to require this sort of cludge, and it'd be easy to fix on the cloud end: have the DHCP server inform the kernel of the IP it's using instead of relying entirely on external translation. Then it'd appear as normal hardware like servers in other colos, like consumer devices when not NATd, etc.

In our case we can run our own checkip.com type server as part of the network map, then deliver knowledge of the IP address back to the node via a dialback connection. This will sort both the "I don't know my address" problem and the "my admin forgot to set up port forwarding" problem too. Both are problems associated with non-professional home networks than pro-level server hosting, but oh well.

WRT IPv6 and internet of things - it's worth separating addressability from reachability. I fully agree you don't want smart lightbulbs publicly reachable from the internet (hence firewalls are still useful in IPv6), but they should be publicly addressable. Otherwise if you do decide you want your IoT device to be accessible globally for some reason, it gets awkward to do it. (AFAIK) all the devices in my home have globally valid IPv6 addresses.

It'd be convenient if a machine in a service like Azure/AWS that had a public IP assigned also had all ports forwarded by default, as the only standard APIs for firewall management are for local firewalls only. As is, we will have to find ways to detect that this step has been forgotten - probably a timeout whilst waiting for dialback.

**Comment by wawrzek** [comment] 2017-02-27 13:41
Azure/AWS machine with public IP address has all ports forwarded by default.

The problem is with Corda not be able to translate node-name to local IP address. Adding node-name to /etc/hosts instantly resolve the problem.

**Comment by mikehearn** [comment] 2017-02-27 15:47
OK, that's a quick workaround we can add for M9 perhaps - check if the node name resolves to an internal IP range and if so, print out instructions for adding an entry to /etc/hosts

When I set up a test box on Azure, I opened a web server on port 8080 but connections didn't work until I explicitly configured a port forward, even though it had a public IP. Seems like there may be different setup procedures involved or something?

**Comment by wawrzek** [comment] 2017-03-03 23:02
I just run another test with recent Master and problem is gone. Before closing I'm going to do more testing.

**Comment by mikehearn** [comment] 2017-03-06 13:59
I can't think of any reason why it would have gone though - don't think we changed anything related to that. It suggests maybe the problem we're chasing here has a different cause. The original exception is saying that the node can't connect to _itself_ after all. Whilst not knowing its own IP will definitely cause problems, perhaps the specific issue we're hitting first is unrelated.

**Comment by wawrzek** [comment] 2017-03-06 15:12
@evilkid - I try to repeat the faulty scenario and cannot now - Corda starts with 'blank' /etc/hosts (not only master, but older releases). You had similar problem, but different configuration and I wonder if you can recreate the issue.

**Comment by evilkid** [comment] 2017-03-07 15:34
@wawrzek I still run through the same problems (Master branch), tried with both "localhost" and public address on the artemisAddress. When using the public address i get the: 
"org.apache.activemq.artemis.api.core.ActiveMQNotConnectedException: AMQ119007: Cannot connect to server(s). Tried with all available servers." 
And using the default values the node dosn't get registered to the network service.

**Comment by tk1993** [comment] 2018-12-07 10:31
Trying to connect Corda nodes through CordaRPCConnection which  is setup on Azure got the same error 
**ActiveMQNotConnectedException[errorType=NOT_CONNECTED message=AMQ119007: Cannot connect to server(s). Tried with all available servers.]**

Also tried by giving node name and ip but still got the same error.

**Comment by wawrzek** [comment] 2018-12-07 12:30
@tk1993 - is that on Azure?

**Comment by tk1993** [comment] 2018-12-11 07:12
@wawrzek Any update on this issue..?

**Comment by tk1993** [comment] 2018-12-13 11:31
Successfully resolved the issue :)
Approach : While deploying nodes change the IP of nodes from localhost to 0.0.0.0 because if you give 127.0.0.1 then network adopter  will communicate within same host A process that is listening on 127.0.0.1 for connections will only receive local connections on that socket.When a server is told to listen on  0.0.0.0 that means "listen on every available network interface.To prevent unauthorized users we can use SSL handshake.

**Comment by mikehearn** [comment] 2018-12-13 12:56
Great!

**Closed by mikehearn** 2018-12-13 12:56 UTC
Labels: enhancement
